// Generates src/version.ts from package.json.
//
// The version was duplicated in both files, so `npm version` bumped one and
// left the CLI reporting the old number — and the collector sends that string
// to the server as `collectorVersion`, so the drift would have been recorded
// against every ingested session.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const pkg = JSON.parse(readFileSync(join(here, "..", "package.json"), "utf8"));

writeFileSync(
  join(here, "..", "src", "version.ts"),
  `// Generated by scripts/gen-version.mjs — edit package.json instead.\nexport const VERSION = "${pkg.version}";\n`,
);
console.log(`version.ts -> ${pkg.version}`);
